spring.datasource.url=jdbc:postgresql://localhost:5432/manager_system
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

# 1. Mostra o SQL formatado e legível
spring.jpa.properties.hibernate.format_sql=true

# 2. Mostra as mensagens do Spring abrindo, usando e fechando transações
logging.level.org.springframework.transaction=debug